#ifndef GUARD_CONSTANTS_GYM_LEADER_H
#define GUARD_CONSTANTS_GYM_LEADER_H

#define VAR_GYM_SPECIALTY_TYPE        0x40D0
#define VAR_GYM_RANK                  0x40D1
#define VAR_GYM_REPUTATION            0x40D2
#define VAR_GYM_BUDGET                0x40D3
#define VAR_GYM_DEFENSE_COUNT         0x40D4
#define VAR_GYM_WIN_STREAK            0x40D5
#define VAR_GYM_BADGES_ISSUED         0x40D6
#define VAR_GYM_WEEK                  0x40D7
#define VAR_GYM_CHALLENGER_SEED       0x40D8
#define VAR_GYM_UPGRADES              0x40D9
#define VAR_GYM_LAST_RESULT           0x40DA
#define VAR_GYM_INSPECTION_PROGRESS   0x40DB
#define VAR_GYM_SIGNATURE_SPECIES     0x40DC
#define VAR_GYM_RULESET               0x40DD

#define GYM_RESULT_NONE 0
#define GYM_RESULT_WIN  1
#define GYM_RESULT_LOSS 2

enum GymSpecialty
{
    GYM_SPECIALTY_NORMAL,
    GYM_SPECIALTY_FIGHTING,
    GYM_SPECIALTY_FLYING,
    GYM_SPECIALTY_POISON,
    GYM_SPECIALTY_GROUND,
    GYM_SPECIALTY_ROCK,
    GYM_SPECIALTY_BUG,
    GYM_SPECIALTY_GHOST,
    GYM_SPECIALTY_STEEL,
    GYM_SPECIALTY_FIRE,
    GYM_SPECIALTY_WATER,
    GYM_SPECIALTY_GRASS,
    GYM_SPECIALTY_ELECTRIC,
    GYM_SPECIALTY_PSYCHIC,
    GYM_SPECIALTY_ICE,
    GYM_SPECIALTY_DRAGON,
    GYM_SPECIALTY_DARK,
    GYM_SPECIALTY_FAIRY,
    GYM_SPECIALTY_COUNT
};

#define GYM_RULESET_STRICT_MONOTYPE 0
#define GYM_RULESET_ONE_WILDCARD    1

#define GYM_UPGRADE_HEAL_STATION     (1 << 0)
#define GYM_UPGRADE_TRAINING_ROOM    (1 << 1)
#define GYM_UPGRADE_SECOND_TRAINER   (1 << 2)
#define GYM_UPGRADE_PUZZLE_BASIC     (1 << 3)
#define GYM_UPGRADE_PUZZLE_ADVANCED  (1 << 4)
#define GYM_UPGRADE_SHOWCASE_ROOM    (1 << 5)
#define GYM_UPGRADE_SCOUT_DESK       (1 << 6)
#define GYM_UPGRADE_LEAGUE_BANNER    (1 << 7)

#endif // GUARD_CONSTANTS_GYM_LEADER_H
